# Generated by Django 2.2.1 on 2020-06-29 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_text', models.CharField(max_length=120)),
                ('text_type', models.CharField(choices=[('MARKDOWN', 'MARKDOWN'), ('HTML', 'HTML'), ('LATEX', 'LATEX'), ('TEXT', 'TEXT')], max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('output_text', models.TextField()),
                ('score', models.IntegerField()),
                ('is_hidden', models.BooleanField(default=True)),
                ('order_id', models.IntegerField(default=1)),
                ('user_id', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management_portal.Question')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionApproach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description_content_type', models.CharField(choices=[('MARKDOWN', 'MARKDOWN'), ('HTML', 'HTML'), ('LATEX', 'LATEX'), ('TEXT', 'TEXT')], max_length=100)),
                ('description_content', models.TextField()),
                ('complexity_content_type', models.CharField(choices=[('MARKDOWN', 'MARKDOWN'), ('HTML', 'HTML'), ('LATEX', 'LATEX'), ('TEXT', 'TEXT')], max_length=100)),
                ('complexity_content', models.TextField()),
                ('user_id', models.IntegerField()),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='content_management_portal.Question')),
            ],
        ),
        migrations.CreateModel(
            name='RoughSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=120)),
                ('language', models.CharField(choices=[('PYTHON', 'PYTHON'), ('JAVA', 'JAVA'), ('C', 'C'), ('RUBY', 'RUBY'), ('CPP', 'CPP'), ('CS', 'CS'), ('JAVASCRIPT', 'JAVASCRIPT'), ('PHP', 'PHP')], max_length=100)),
                ('code', models.TextField()),
                ('user_id', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management_portal.Question')),
            ],
        ),
        migrations.CreateModel(
            name='PrefilledCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=120)),
                ('language', models.CharField(choices=[('PYTHON', 'PYTHON'), ('JAVA', 'JAVA'), ('C', 'C'), ('RUBY', 'RUBY'), ('CPP', 'CPP'), ('CS', 'CS'), ('JAVASCRIPT', 'JAVASCRIPT'), ('PHP', 'PHP')], max_length=100)),
                ('code', models.TextField()),
                ('user_id', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management_portal.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content_type', models.CharField(choices=[('MARKDOWN', 'MARKDOWN'), ('HTML', 'HTML'), ('LATEX', 'LATEX'), ('TEXT', 'TEXT')], max_length=100)),
                ('content', models.TextField()),
                ('order_id', models.IntegerField(default=1)),
                ('user_id', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management_portal.Question')),
            ],
        ),
        migrations.CreateModel(
            name='CleanSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=120)),
                ('language', models.CharField(choices=[('PYTHON', 'PYTHON'), ('JAVA', 'JAVA'), ('C', 'C'), ('RUBY', 'RUBY'), ('CPP', 'CPP'), ('CS', 'CS'), ('JAVASCRIPT', 'JAVASCRIPT'), ('PHP', 'PHP')], max_length=100)),
                ('code', models.TextField()),
                ('user_id', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management_portal.Question')),
            ],
        ),
    ]
